---
- name: Ansible playbook interacting with 
  hosts: localhost
  connection: local
  
  vars:
    # replace i=tt3896198 with s=shrek then try again!
      apod_url: "http://www.omdbapi.com/?s=shrek&apikey=" # API to call
      mykey: "{{ lookup('file', '~/nasa.key') }}"  # our api key

  tasks:
  - name: Send HTTP GET to NASA api
    uri:
      method: GET     # send this method
      url: "{{ apod_url }}{{ mykey }}"
    register: nasaread
    
  - name: Display the contents of the variable 'nasaread'
    debug:
      var: nasaread
